# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(843, 535)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(9, 9, 352, 477))
        self.widget.setObjectName("widget")
        self.gridLayout = QtWidgets.QGridLayout(self.widget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.Casing2 = QtWidgets.QVBoxLayout()
        self.Casing2.setObjectName("Casing2")
        self.label_5 = QtWidgets.QLabel(self.widget)
        self.label_5.setObjectName("label_5")
        self.Casing2.addWidget(self.label_5)
        self.formLayout_2 = QtWidgets.QFormLayout()
        self.formLayout_2.setObjectName("formLayout_2")
        self.label_6 = QtWidgets.QLabel(self.widget)
        self.label_6.setObjectName("label_6")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_6)
        self.lineEdit_4 = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.lineEdit_4)
        self.label_7 = QtWidgets.QLabel(self.widget)
        self.label_7.setObjectName("label_7")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_7)
        self.lineEdit_5 = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.lineEdit_5)
        self.label_8 = QtWidgets.QLabel(self.widget)
        self.label_8.setObjectName("label_8")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_8)
        self.lineEdit_6 = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_6.setObjectName("lineEdit_6")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.lineEdit_6)
        self.Label_2 = QtWidgets.QLabel(self.widget)
        self.Label_2.setObjectName("Label_2")
        self.formLayout_2.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.Label_2)
        self.LineEdit_2 = QtWidgets.QLineEdit(self.widget)
        self.LineEdit_2.setObjectName("LineEdit_2")
        self.formLayout_2.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.LineEdit_2)
        self.Casing2.addLayout(self.formLayout_2)
        self.gridLayout.addLayout(self.Casing2, 1, 0, 1, 1)
        self.Casing3 = QtWidgets.QVBoxLayout()
        self.Casing3.setObjectName("Casing3")
        self.label_9 = QtWidgets.QLabel(self.widget)
        self.label_9.setObjectName("label_9")
        self.Casing3.addWidget(self.label_9)
        self.formLayout_3 = QtWidgets.QFormLayout()
        self.formLayout_3.setObjectName("formLayout_3")
        self.label_10 = QtWidgets.QLabel(self.widget)
        self.label_10.setObjectName("label_10")
        self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_10)
        self.lineEdit_7 = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_7.setObjectName("lineEdit_7")
        self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.lineEdit_7)
        self.lineEdit_8 = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_8.setObjectName("lineEdit_8")
        self.formLayout_3.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.lineEdit_8)
        self.label_11 = QtWidgets.QLabel(self.widget)
        self.label_11.setObjectName("label_11")
        self.formLayout_3.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_11)
        self.lineEdit_9 = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_9.setObjectName("lineEdit_9")
        self.formLayout_3.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.lineEdit_9)
        self.label_12 = QtWidgets.QLabel(self.widget)
        self.label_12.setObjectName("label_12")
        self.formLayout_3.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_12)
        self.Label_3 = QtWidgets.QLabel(self.widget)
        self.Label_3.setObjectName("Label_3")
        self.formLayout_3.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.Label_3)
        self.LineEdit_3 = QtWidgets.QLineEdit(self.widget)
        self.LineEdit_3.setObjectName("LineEdit_3")
        self.formLayout_3.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.LineEdit_3)
        self.Casing3.addLayout(self.formLayout_3)
        self.gridLayout.addLayout(self.Casing3, 2, 0, 1, 1)
        self.thermal = QtWidgets.QVBoxLayout()
        self.thermal.setObjectName("thermal")
        self.label_15 = QtWidgets.QLabel(self.widget)
        self.label_15.setObjectName("label_15")
        self.thermal.addWidget(self.label_15)
        self.formLayout_5 = QtWidgets.QFormLayout()
        self.formLayout_5.setObjectName("formLayout_5")
        self.label_16 = QtWidgets.QLabel(self.widget)
        self.label_16.setObjectName("label_16")
        self.formLayout_5.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_16)
        self.lineEdit_11 = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_11.setObjectName("lineEdit_11")
        self.formLayout_5.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.lineEdit_11)
        self.tDLabel = QtWidgets.QLabel(self.widget)
        self.tDLabel.setObjectName("tDLabel")
        self.formLayout_5.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.tDLabel)
        self.tDLineEdit = QtWidgets.QLineEdit(self.widget)
        self.tDLineEdit.setObjectName("tDLineEdit")
        self.formLayout_5.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.tDLineEdit)
        self.jKgLLabel = QtWidgets.QLabel(self.widget)
        self.jKgLLabel.setObjectName("jKgLLabel")
        self.formLayout_5.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.jKgLLabel)
        self.jKgLLineEdit = QtWidgets.QLineEdit(self.widget)
        self.jKgLLineEdit.setObjectName("jKgLLineEdit")
        self.formLayout_5.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.jKgLLineEdit)
        self.jKgKLabel = QtWidgets.QLabel(self.widget)
        self.jKgKLabel.setObjectName("jKgKLabel")
        self.formLayout_5.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.jKgKLabel)
        self.jKgKLineEdit = QtWidgets.QLineEdit(self.widget)
        self.jKgKLineEdit.setObjectName("jKgKLineEdit")
        self.formLayout_5.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.jKgKLineEdit)
        self.wM2KLabel = QtWidgets.QLabel(self.widget)
        self.wM2KLabel.setObjectName("wM2KLabel")
        self.formLayout_5.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.wM2KLabel)
        self.wM2KLineEdit = QtWidgets.QLineEdit(self.widget)
        self.wM2KLineEdit.setObjectName("wM2KLineEdit")
        self.formLayout_5.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.wM2KLineEdit)
        self.wMKLabel = QtWidgets.QLabel(self.widget)
        self.wMKLabel.setObjectName("wMKLabel")
        self.formLayout_5.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.wMKLabel)
        self.wMKLineEdit = QtWidgets.QLineEdit(self.widget)
        self.wMKLineEdit.setObjectName("wMKLineEdit")
        self.formLayout_5.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.wMKLineEdit)
        self.wMKLabel_2 = QtWidgets.QLabel(self.widget)
        self.wMKLabel_2.setObjectName("wMKLabel_2")
        self.formLayout_5.setWidget(6, QtWidgets.QFormLayout.LabelRole, self.wMKLabel_2)
        self.wMKLineEdit_2 = QtWidgets.QLineEdit(self.widget)
        self.wMKLineEdit_2.setObjectName("wMKLineEdit_2")
        self.formLayout_5.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.wMKLineEdit_2)
        self.wMKLabel_3 = QtWidgets.QLabel(self.widget)
        self.wMKLabel_3.setObjectName("wMKLabel_3")
        self.formLayout_5.setWidget(7, QtWidgets.QFormLayout.LabelRole, self.wMKLabel_3)
        self.wMKLineEdit_3 = QtWidgets.QLineEdit(self.widget)
        self.wMKLineEdit_3.setObjectName("wMKLineEdit_3")
        self.formLayout_5.setWidget(7, QtWidgets.QFormLayout.FieldRole, self.wMKLineEdit_3)
        self.wMKLabel_4 = QtWidgets.QLabel(self.widget)
        self.wMKLabel_4.setObjectName("wMKLabel_4")
        self.formLayout_5.setWidget(8, QtWidgets.QFormLayout.LabelRole, self.wMKLabel_4)
        self.wMKLineEdit_4 = QtWidgets.QLineEdit(self.widget)
        self.wMKLineEdit_4.setObjectName("wMKLineEdit_4")
        self.formLayout_5.setWidget(8, QtWidgets.QFormLayout.FieldRole, self.wMKLineEdit_4)
        self.kgM3Label = QtWidgets.QLabel(self.widget)
        self.kgM3Label.setObjectName("kgM3Label")
        self.formLayout_5.setWidget(9, QtWidgets.QFormLayout.LabelRole, self.kgM3Label)
        self.kgM3LineEdit = QtWidgets.QLineEdit(self.widget)
        self.kgM3LineEdit.setObjectName("kgM3LineEdit")
        self.formLayout_5.setWidget(9, QtWidgets.QFormLayout.FieldRole, self.kgM3LineEdit)
        self.kgM3Label_2 = QtWidgets.QLabel(self.widget)
        self.kgM3Label_2.setObjectName("kgM3Label_2")
        self.formLayout_5.setWidget(10, QtWidgets.QFormLayout.LabelRole, self.kgM3Label_2)
        self.kgM3LineEdit_2 = QtWidgets.QLineEdit(self.widget)
        self.kgM3LineEdit_2.setObjectName("kgM3LineEdit_2")
        self.formLayout_5.setWidget(10, QtWidgets.QFormLayout.FieldRole, self.kgM3LineEdit_2)
        self.m2SLabel = QtWidgets.QLabel(self.widget)
        self.m2SLabel.setObjectName("m2SLabel")
        self.formLayout_5.setWidget(11, QtWidgets.QFormLayout.LabelRole, self.m2SLabel)
        self.m2SLineEdit = QtWidgets.QLineEdit(self.widget)
        self.m2SLineEdit.setObjectName("m2SLineEdit")
        self.formLayout_5.setWidget(11, QtWidgets.QFormLayout.FieldRole, self.m2SLineEdit)
        self.Label_4 = QtWidgets.QLabel(self.widget)
        self.Label_4.setObjectName("Label_4")
        self.formLayout_5.setWidget(12, QtWidgets.QFormLayout.LabelRole, self.Label_4)
        self.LineEdit_4 = QtWidgets.QLineEdit(self.widget)
        self.LineEdit_4.setObjectName("LineEdit_4")
        self.formLayout_5.setWidget(12, QtWidgets.QFormLayout.FieldRole, self.LineEdit_4)
        self.thermal.addLayout(self.formLayout_5)
        self.gridLayout.addLayout(self.thermal, 0, 1, 3, 1)
        self.well_etc = QtWidgets.QVBoxLayout()
        self.well_etc.setObjectName("well_etc")
        self.label_13 = QtWidgets.QLabel(self.widget)
        self.label_13.setObjectName("label_13")
        self.well_etc.addWidget(self.label_13)
        self.formLayout_4 = QtWidgets.QFormLayout()
        self.formLayout_4.setObjectName("formLayout_4")
        self.label_14 = QtWidgets.QLabel(self.widget)
        self.label_14.setObjectName("label_14")
        self.formLayout_4.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_14)
        self.lineEdit_10 = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_10.setObjectName("lineEdit_10")
        self.formLayout_4.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.lineEdit_10)
        self.dLabel = QtWidgets.QLabel(self.widget)
        self.dLabel.setObjectName("dLabel")
        self.formLayout_4.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.dLabel)
        self.dLineEdit = QtWidgets.QLineEdit(self.widget)
        self.dLineEdit.setObjectName("dLineEdit")
        self.formLayout_4.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.dLineEdit)
        self.well_etc.addLayout(self.formLayout_4)
        self.gridLayout.addLayout(self.well_etc, 3, 0, 1, 1)
        self.Casing1 = QtWidgets.QVBoxLayout()
        self.Casing1.setObjectName("Casing1")
        self.label_2 = QtWidgets.QLabel(self.widget)
        self.label_2.setObjectName("label_2")
        self.Casing1.addWidget(self.label_2)
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setObjectName("formLayout")
        self.label = QtWidgets.QLabel(self.widget)
        self.label.setObjectName("label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label)
        self.lineEdit = QtWidgets.QLineEdit(self.widget)
        self.lineEdit.setObjectName("lineEdit")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.lineEdit)
        self.label_3 = QtWidgets.QLabel(self.widget)
        self.label_3.setObjectName("label_3")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.lineEdit_2 = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.lineEdit_2)
        self.label_4 = QtWidgets.QLabel(self.widget)
        self.label_4.setObjectName("label_4")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_4)
        self.lineEdit_3 = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.lineEdit_3)
        self.Label = QtWidgets.QLabel(self.widget)
        self.Label.setObjectName("Label")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.Label)
        self.LineEdit = QtWidgets.QLineEdit(self.widget)
        self.LineEdit.setObjectName("LineEdit")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.LineEdit)
        self.Casing1.addLayout(self.formLayout)
        self.gridLayout.addLayout(self.Casing1, 0, 0, 1, 1)
        self.pushButton = QtWidgets.QPushButton(self.widget)
        self.pushButton.setObjectName("pushButton")
        self.gridLayout.addWidget(self.pushButton, 3, 1, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 843, 23))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "APB计算器"))
        self.label_5.setText(_translate("MainWindow", "技术套管"))
        self.label_6.setText(_translate("MainWindow", "深度 m"))
        self.label_7.setText(_translate("MainWindow", "外径 in"))
        self.label_8.setText(_translate("MainWindow", "内径 m"))
        self.Label_2.setText(_translate("MainWindow", "水泥返高 m"))
        self.label_9.setText(_translate("MainWindow", "表层套管"))
        self.label_10.setText(_translate("MainWindow", "深度 m"))
        self.label_11.setText(_translate("MainWindow", "外径 in"))
        self.label_12.setText(_translate("MainWindow", "内径 in"))
        self.Label_3.setText(_translate("MainWindow", "水泥返高 m"))
        self.label_15.setText(_translate("MainWindow", "热力学参数"))
        self.label_16.setText(_translate("MainWindow", "地温梯度 ℃/m"))
        self.tDLabel.setText(_translate("MainWindow", "流量 t/d"))
        self.jKgLLabel.setText(_translate("MainWindow", "产液比热容 J/(kg*L)"))
        self.jKgKLabel.setText(_translate("MainWindow", "环空液体比热容 J/(kg*K)"))
        self.wM2KLabel.setText(_translate("MainWindow", "对流换热系数 W(m2*K)"))
        self.wMKLabel.setText(_translate("MainWindow", "套管导热系数 W/(m*K)"))
        self.wMKLabel_2.setText(_translate("MainWindow", "油管导热系数 W(m*K)"))
        self.wMKLabel_3.setText(_translate("MainWindow", "环空液体导热系数 W/(m*K)"))
        self.wMKLabel_4.setText(_translate("MainWindow", "水泥环导热系数 W/(m*K)"))
        self.kgM3Label.setText(_translate("MainWindow", "产液密度 kg/m3"))
        self.kgM3Label_2.setText(_translate("MainWindow", "环空液体密度 kg/m3"))
        self.m2SLabel.setText(_translate("MainWindow", "地层热扩散系数 m2/s"))
        self.Label_4.setText(_translate("MainWindow", "井口温度 ℃"))
        self.label_13.setText(_translate("MainWindow", "其他"))
        self.label_14.setText(_translate("MainWindow", "外层水泥环厚度 mm"))
        self.dLabel.setText(_translate("MainWindow", "生产时间 d"))
        self.label_2.setText(_translate("MainWindow", "油层套管"))
        self.label.setText(_translate("MainWindow", "深度 m"))
        self.label_3.setText(_translate("MainWindow", "外径 in"))
        self.label_4.setText(_translate("MainWindow", "内径 in"))
        self.Label.setText(_translate("MainWindow", "水泥返高 m"))
        self.pushButton.setText(_translate("MainWindow", "保存"))

