# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(843, 572)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.buttonRun = QtWidgets.QPushButton(self.centralwidget)
        self.buttonRun.setGeometry(QtCore.QRect(180, 500, 75, 23))
        self.buttonRun.setObjectName("buttonRun")
        self.label_message = QtWidgets.QLabel(self.centralwidget)
        self.label_message.setGeometry(QtCore.QRect(260, 500, 91, 21))
        self.label_message.setText("")
        self.label_message.setObjectName("label_message")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(400, 10, 421, 321))
        self.groupBox.setObjectName("groupBox")
        self.label_temp_image = QtWidgets.QLabel(self.groupBox)
        self.label_temp_image.setGeometry(QtCore.QRect(10, 20, 401, 291))
        self.label_temp_image.setAutoFillBackground(True)
        self.label_temp_image.setText("")
        self.label_temp_image.setObjectName("label_temp_image")
        self.groupBox_2 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_2.setGeometry(QtCore.QRect(9, 9, 381, 481))
        self.groupBox_2.setObjectName("groupBox_2")
        self.verticalLayoutWidget_6 = QtWidgets.QWidget(self.groupBox_2)
        self.verticalLayoutWidget_6.setGeometry(QtCore.QRect(11, 401, 131, 61))
        self.verticalLayoutWidget_6.setObjectName("verticalLayoutWidget_6")
        self.Tubing = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_6)
        self.Tubing.setContentsMargins(0, 0, 0, 0)
        self.Tubing.setObjectName("Tubing")
        self.label_17 = QtWidgets.QLabel(self.verticalLayoutWidget_6)
        self.label_17.setObjectName("label_17")
        self.Tubing.addWidget(self.label_17)
        self.formLayout_6 = QtWidgets.QFormLayout()
        self.formLayout_6.setObjectName("formLayout_6")
        self.label_19 = QtWidgets.QLabel(self.verticalLayoutWidget_6)
        self.label_19.setObjectName("label_19")
        self.formLayout_6.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_19)
        self.input_dto = QtWidgets.QLineEdit(self.verticalLayoutWidget_6)
        self.input_dto.setObjectName("input_dto")
        self.formLayout_6.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.input_dto)
        self.label_20 = QtWidgets.QLabel(self.verticalLayoutWidget_6)
        self.label_20.setObjectName("label_20")
        self.formLayout_6.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_20)
        self.input_dti = QtWidgets.QLineEdit(self.verticalLayoutWidget_6)
        self.input_dti.setObjectName("input_dti")
        self.formLayout_6.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.input_dti)
        self.Tubing.addLayout(self.formLayout_6)
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(self.groupBox_2)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(10, 146, 131, 120))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.Casing2 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.Casing2.setContentsMargins(0, 0, 0, 0)
        self.Casing2.setObjectName("Casing2")
        self.label_5 = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.label_5.setObjectName("label_5")
        self.Casing2.addWidget(self.label_5)
        self.formLayout_2 = QtWidgets.QFormLayout()
        self.formLayout_2.setObjectName("formLayout_2")
        self.label_6 = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.label_6.setObjectName("label_6")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_6)
        self.input_depth2 = QtWidgets.QLineEdit(self.verticalLayoutWidget_2)
        self.input_depth2.setObjectName("input_depth2")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.input_depth2)
        self.label_7 = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.label_7.setObjectName("label_7")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_7)
        self.input_dc2o = QtWidgets.QLineEdit(self.verticalLayoutWidget_2)
        self.input_dc2o.setObjectName("input_dc2o")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.input_dc2o)
        self.label_8 = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.label_8.setObjectName("label_8")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_8)
        self.input_dc2i = QtWidgets.QLineEdit(self.verticalLayoutWidget_2)
        self.input_dc2i.setObjectName("input_dc2i")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.input_dc2i)
        self.Label_2 = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.Label_2.setObjectName("Label_2")
        self.formLayout_2.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.Label_2)
        self.input_toc2 = QtWidgets.QLineEdit(self.verticalLayoutWidget_2)
        self.input_toc2.setObjectName("input_toc2")
        self.formLayout_2.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.input_toc2)
        self.Casing2.addLayout(self.formLayout_2)
        self.verticalLayoutWidget_5 = QtWidgets.QWidget(self.groupBox_2)
        self.verticalLayoutWidget_5.setGeometry(QtCore.QRect(151, 21, 221, 371))
        self.verticalLayoutWidget_5.setObjectName("verticalLayoutWidget_5")
        self.thermal = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_5)
        self.thermal.setContentsMargins(0, 0, 0, 0)
        self.thermal.setObjectName("thermal")
        self.label_15 = QtWidgets.QLabel(self.verticalLayoutWidget_5)
        self.label_15.setObjectName("label_15")
        self.thermal.addWidget(self.label_15)
        self.formLayout_5 = QtWidgets.QFormLayout()
        self.formLayout_5.setObjectName("formLayout_5")
        self.label_16 = QtWidgets.QLabel(self.verticalLayoutWidget_5)
        self.label_16.setObjectName("label_16")
        self.formLayout_5.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_16)
        self.input_m = QtWidgets.QLineEdit(self.verticalLayoutWidget_5)
        self.input_m.setObjectName("input_m")
        self.formLayout_5.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.input_m)
        self.tDLabel = QtWidgets.QLabel(self.verticalLayoutWidget_5)
        self.tDLabel.setObjectName("tDLabel")
        self.formLayout_5.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.tDLabel)
        self.input_W = QtWidgets.QLineEdit(self.verticalLayoutWidget_5)
        self.input_W.setObjectName("input_W")
        self.formLayout_5.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.input_W)
        self.jKgLLabel = QtWidgets.QLabel(self.verticalLayoutWidget_5)
        self.jKgLLabel.setObjectName("jKgLLabel")
        self.formLayout_5.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.jKgLLabel)
        self.input_cp_oil = QtWidgets.QLineEdit(self.verticalLayoutWidget_5)
        self.input_cp_oil.setObjectName("input_cp_oil")
        self.formLayout_5.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.input_cp_oil)
        self.jKgKLabel = QtWidgets.QLabel(self.verticalLayoutWidget_5)
        self.jKgKLabel.setObjectName("jKgKLabel")
        self.formLayout_5.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.jKgKLabel)
        self.input_cp_annular = QtWidgets.QLineEdit(self.verticalLayoutWidget_5)
        self.input_cp_annular.setObjectName("input_cp_annular")
        self.formLayout_5.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.input_cp_annular)
        self.wM2KLabel = QtWidgets.QLabel(self.verticalLayoutWidget_5)
        self.wM2KLabel.setObjectName("wM2KLabel")
        self.formLayout_5.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.wM2KLabel)
        self.input_h = QtWidgets.QLineEdit(self.verticalLayoutWidget_5)
        self.input_h.setObjectName("input_h")
        self.formLayout_5.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.input_h)
        self.wMKLabel = QtWidgets.QLabel(self.verticalLayoutWidget_5)
        self.wMKLabel.setObjectName("wMKLabel")
        self.formLayout_5.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.wMKLabel)
        self.input_Kc = QtWidgets.QLineEdit(self.verticalLayoutWidget_5)
        self.input_Kc.setObjectName("input_Kc")
        self.formLayout_5.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.input_Kc)
        self.wMKLabel_2 = QtWidgets.QLabel(self.verticalLayoutWidget_5)
        self.wMKLabel_2.setObjectName("wMKLabel_2")
        self.formLayout_5.setWidget(6, QtWidgets.QFormLayout.LabelRole, self.wMKLabel_2)
        self.input_Kt = QtWidgets.QLineEdit(self.verticalLayoutWidget_5)
        self.input_Kt.setObjectName("input_Kt")
        self.formLayout_5.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.input_Kt)
        self.wMKLabel_3 = QtWidgets.QLabel(self.verticalLayoutWidget_5)
        self.wMKLabel_3.setObjectName("wMKLabel_3")
        self.formLayout_5.setWidget(7, QtWidgets.QFormLayout.LabelRole, self.wMKLabel_3)
        self.input_Ka = QtWidgets.QLineEdit(self.verticalLayoutWidget_5)
        self.input_Ka.setObjectName("input_Ka")
        self.formLayout_5.setWidget(7, QtWidgets.QFormLayout.FieldRole, self.input_Ka)
        self.wMKLabel_4 = QtWidgets.QLabel(self.verticalLayoutWidget_5)
        self.wMKLabel_4.setObjectName("wMKLabel_4")
        self.formLayout_5.setWidget(8, QtWidgets.QFormLayout.LabelRole, self.wMKLabel_4)
        self.input_Kcem = QtWidgets.QLineEdit(self.verticalLayoutWidget_5)
        self.input_Kcem.setObjectName("input_Kcem")
        self.formLayout_5.setWidget(8, QtWidgets.QFormLayout.FieldRole, self.input_Kcem)
        self.wMKLabel_5 = QtWidgets.QLabel(self.verticalLayoutWidget_5)
        self.wMKLabel_5.setObjectName("wMKLabel_5")
        self.formLayout_5.setWidget(9, QtWidgets.QFormLayout.LabelRole, self.wMKLabel_5)
        self.input_Ke = QtWidgets.QLineEdit(self.verticalLayoutWidget_5)
        self.input_Ke.setObjectName("input_Ke")
        self.formLayout_5.setWidget(9, QtWidgets.QFormLayout.FieldRole, self.input_Ke)
        self.kgM3Label = QtWidgets.QLabel(self.verticalLayoutWidget_5)
        self.kgM3Label.setObjectName("kgM3Label")
        self.formLayout_5.setWidget(10, QtWidgets.QFormLayout.LabelRole, self.kgM3Label)
        self.input_density_oil = QtWidgets.QLineEdit(self.verticalLayoutWidget_5)
        self.input_density_oil.setObjectName("input_density_oil")
        self.formLayout_5.setWidget(10, QtWidgets.QFormLayout.FieldRole, self.input_density_oil)
        self.kgM3Label_2 = QtWidgets.QLabel(self.verticalLayoutWidget_5)
        self.kgM3Label_2.setObjectName("kgM3Label_2")
        self.formLayout_5.setWidget(11, QtWidgets.QFormLayout.LabelRole, self.kgM3Label_2)
        self.input_density_annular = QtWidgets.QLineEdit(self.verticalLayoutWidget_5)
        self.input_density_annular.setObjectName("input_density_annular")
        self.formLayout_5.setWidget(11, QtWidgets.QFormLayout.FieldRole, self.input_density_annular)
        self.m2SLabel = QtWidgets.QLabel(self.verticalLayoutWidget_5)
        self.m2SLabel.setObjectName("m2SLabel")
        self.formLayout_5.setWidget(12, QtWidgets.QFormLayout.LabelRole, self.m2SLabel)
        self.input_ae = QtWidgets.QLineEdit(self.verticalLayoutWidget_5)
        self.input_ae.setObjectName("input_ae")
        self.formLayout_5.setWidget(12, QtWidgets.QFormLayout.FieldRole, self.input_ae)
        self.Label_4 = QtWidgets.QLabel(self.verticalLayoutWidget_5)
        self.Label_4.setObjectName("Label_4")
        self.formLayout_5.setWidget(13, QtWidgets.QFormLayout.LabelRole, self.Label_4)
        self.input_temp_surface = QtWidgets.QLineEdit(self.verticalLayoutWidget_5)
        self.input_temp_surface.setObjectName("input_temp_surface")
        self.formLayout_5.setWidget(13, QtWidgets.QFormLayout.FieldRole, self.input_temp_surface)
        self.thermal.addLayout(self.formLayout_5)
        self.verticalLayoutWidget_4 = QtWidgets.QWidget(self.groupBox_2)
        self.verticalLayoutWidget_4.setGeometry(QtCore.QRect(151, 401, 221, 68))
        self.verticalLayoutWidget_4.setObjectName("verticalLayoutWidget_4")
        self.well_etc = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_4)
        self.well_etc.setContentsMargins(0, 0, 0, 0)
        self.well_etc.setObjectName("well_etc")
        self.label_13 = QtWidgets.QLabel(self.verticalLayoutWidget_4)
        self.label_13.setObjectName("label_13")
        self.well_etc.addWidget(self.label_13)
        self.formLayout_4 = QtWidgets.QFormLayout()
        self.formLayout_4.setObjectName("formLayout_4")
        self.label_14 = QtWidgets.QLabel(self.verticalLayoutWidget_4)
        self.label_14.setObjectName("label_14")
        self.formLayout_4.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_14)
        self.input_tcem = QtWidgets.QLineEdit(self.verticalLayoutWidget_4)
        self.input_tcem.setObjectName("input_tcem")
        self.formLayout_4.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.input_tcem)
        self.dLabel = QtWidgets.QLabel(self.verticalLayoutWidget_4)
        self.dLabel.setObjectName("dLabel")
        self.formLayout_4.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.dLabel)
        self.input_t = QtWidgets.QLineEdit(self.verticalLayoutWidget_4)
        self.input_t.setObjectName("input_t")
        self.formLayout_4.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.input_t)
        self.well_etc.addLayout(self.formLayout_4)
        self.verticalLayoutWidget = QtWidgets.QWidget(self.groupBox_2)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(10, 20, 131, 120))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.Casing1 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.Casing1.setContentsMargins(0, 0, 0, 0)
        self.Casing1.setObjectName("Casing1")
        self.label_2 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_2.setObjectName("label_2")
        self.Casing1.addWidget(self.label_2)
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setObjectName("formLayout")
        self.label = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label.setObjectName("label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label)
        self.input_depth1 = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.input_depth1.setObjectName("input_depth1")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.input_depth1)
        self.label_3 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_3.setObjectName("label_3")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.input_dc1o = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.input_dc1o.setObjectName("input_dc1o")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.input_dc1o)
        self.label_4 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_4.setObjectName("label_4")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_4)
        self.input_dc1i = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.input_dc1i.setObjectName("input_dc1i")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.input_dc1i)
        self.Label = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.Label.setObjectName("Label")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.Label)
        self.input_toc1 = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.input_toc1.setObjectName("input_toc1")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.input_toc1)
        self.Casing1.addLayout(self.formLayout)
        self.verticalLayoutWidget_3 = QtWidgets.QWidget(self.groupBox_2)
        self.verticalLayoutWidget_3.setGeometry(QtCore.QRect(10, 272, 131, 120))
        self.verticalLayoutWidget_3.setObjectName("verticalLayoutWidget_3")
        self.Casing3 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_3)
        self.Casing3.setContentsMargins(0, 0, 0, 0)
        self.Casing3.setObjectName("Casing3")
        self.label_9 = QtWidgets.QLabel(self.verticalLayoutWidget_3)
        self.label_9.setObjectName("label_9")
        self.Casing3.addWidget(self.label_9)
        self.formLayout_3 = QtWidgets.QFormLayout()
        self.formLayout_3.setObjectName("formLayout_3")
        self.label_10 = QtWidgets.QLabel(self.verticalLayoutWidget_3)
        self.label_10.setObjectName("label_10")
        self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_10)
        self.input_depth3 = QtWidgets.QLineEdit(self.verticalLayoutWidget_3)
        self.input_depth3.setObjectName("input_depth3")
        self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.input_depth3)
        self.input_dc3o = QtWidgets.QLineEdit(self.verticalLayoutWidget_3)
        self.input_dc3o.setObjectName("input_dc3o")
        self.formLayout_3.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.input_dc3o)
        self.label_11 = QtWidgets.QLabel(self.verticalLayoutWidget_3)
        self.label_11.setObjectName("label_11")
        self.formLayout_3.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_11)
        self.input_dc3i = QtWidgets.QLineEdit(self.verticalLayoutWidget_3)
        self.input_dc3i.setObjectName("input_dc3i")
        self.formLayout_3.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.input_dc3i)
        self.label_12 = QtWidgets.QLabel(self.verticalLayoutWidget_3)
        self.label_12.setObjectName("label_12")
        self.formLayout_3.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_12)
        self.Label_3 = QtWidgets.QLabel(self.verticalLayoutWidget_3)
        self.Label_3.setObjectName("Label_3")
        self.formLayout_3.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.Label_3)
        self.input_toc3 = QtWidgets.QLineEdit(self.verticalLayoutWidget_3)
        self.input_toc3.setObjectName("input_toc3")
        self.formLayout_3.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.input_toc3)
        self.Casing3.addLayout(self.formLayout_3)
        self.label_18 = QtWidgets.QLabel(self.centralwidget)
        self.label_18.setGeometry(QtCore.QRect(410, 360, 81, 21))
        self.label_18.setObjectName("label_18")
        self.label_21 = QtWidgets.QLabel(self.centralwidget)
        self.label_21.setGeometry(QtCore.QRect(410, 390, 81, 21))
        self.label_21.setObjectName("label_21")
        self.label_pressure_B = QtWidgets.QLabel(self.centralwidget)
        self.label_pressure_B.setGeometry(QtCore.QRect(500, 360, 71, 21))
        self.label_pressure_B.setObjectName("label_pressure_B")
        self.label_pressure_C = QtWidgets.QLabel(self.centralwidget)
        self.label_pressure_C.setGeometry(QtCore.QRect(500, 390, 71, 21))
        self.label_pressure_C.setObjectName("label_pressure_C")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 843, 23))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "APB计算器"))
        self.buttonRun.setText(_translate("MainWindow", "运行"))
        self.groupBox.setTitle(_translate("MainWindow", "温度分布图"))
        self.groupBox_2.setTitle(_translate("MainWindow", "参数输入"))
        self.label_17.setText(_translate("MainWindow", "油管"))
        self.label_19.setText(_translate("MainWindow", "外径 mm"))
        self.label_20.setText(_translate("MainWindow", "内径 mm"))
        self.label_5.setText(_translate("MainWindow", "技术套管"))
        self.label_6.setText(_translate("MainWindow", "深度 m"))
        self.label_7.setText(_translate("MainWindow", "外径 mm"))
        self.label_8.setText(_translate("MainWindow", "内径 mm"))
        self.Label_2.setText(_translate("MainWindow", "水泥返高 m"))
        self.label_15.setText(_translate("MainWindow", "热力学参数"))
        self.label_16.setText(_translate("MainWindow", "地温梯度 ℃/m"))
        self.tDLabel.setText(_translate("MainWindow", "流量 t/d"))
        self.jKgLLabel.setText(_translate("MainWindow", "产液比热容 J/(kg*L)"))
        self.jKgKLabel.setText(_translate("MainWindow", "环空液体比热容 J/(kg*K)"))
        self.wM2KLabel.setText(_translate("MainWindow", "对流换热系数 W(m2*K)"))
        self.wMKLabel.setText(_translate("MainWindow", "套管导热系数 W/(m*K)"))
        self.wMKLabel_2.setText(_translate("MainWindow", "油管导热系数 W(m*K)"))
        self.wMKLabel_3.setText(_translate("MainWindow", "环空液体导热系数 W/(m*K)"))
        self.wMKLabel_4.setText(_translate("MainWindow", "水泥环导热系数 W/(m*K)"))
        self.wMKLabel_5.setText(_translate("MainWindow", "地层导热系数 W/(m*K)"))
        self.kgM3Label.setText(_translate("MainWindow", "产液密度 kg/m3"))
        self.kgM3Label_2.setText(_translate("MainWindow", "环空液体密度 kg/m3"))
        self.m2SLabel.setText(_translate("MainWindow", "地层热扩散系数 m2/s"))
        self.Label_4.setText(_translate("MainWindow", "井口温度 ℃"))
        self.label_13.setText(_translate("MainWindow", "其他"))
        self.label_14.setText(_translate("MainWindow", "外层水泥环厚度 mm"))
        self.dLabel.setText(_translate("MainWindow", "生产时间 d"))
        self.label_2.setText(_translate("MainWindow", "油层套管"))
        self.label.setText(_translate("MainWindow", "深度 m"))
        self.label_3.setText(_translate("MainWindow", "外径 mm"))
        self.label_4.setText(_translate("MainWindow", "内径 mm"))
        self.Label.setText(_translate("MainWindow", "水泥返高 m"))
        self.label_9.setText(_translate("MainWindow", "表层套管"))
        self.label_10.setText(_translate("MainWindow", "深度 m"))
        self.label_11.setText(_translate("MainWindow", "外径 mm"))
        self.label_12.setText(_translate("MainWindow", "内径 mm"))
        self.Label_3.setText(_translate("MainWindow", "水泥返高 m"))
        self.label_18.setText(_translate("MainWindow", "B环空增压"))
        self.label_21.setText(_translate("MainWindow", "C环空增压"))
        self.label_pressure_B.setText(_translate("MainWindow", "未计算"))
        self.label_pressure_C.setText(_translate("MainWindow", "未计算"))

